import type { Metadata } from "next";
import Navbar from "./components/navbar/Navbar";
import Sidebar from "./components/sidebar/Sidebar";
import Footer from "./components/footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "My Personal Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="layout">
            <header className="navbar">
                <Navbar />
            </header>
            <aside className="sidebar">
                <Sidebar />
            </aside>
            <main className="dashboard">
                {children}
            </main>
            <footer className="footer">
                <Footer />
            </footer>
        </div>
      </body>
    </html>
  );
}
